// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIDrYf05Hwtx94gpq3RGB1Pdno9_b-npE',
    appId: '1:1051700358679:web:4f7ab544c8cd79cd547652',
    messagingSenderId: '1051700358679',
    projectId: 'newsappfinal-c9395',
    authDomain: 'newsappfinal-c9395.firebaseapp.com',
    storageBucket: 'newsappfinal-c9395.appspot.com',
    measurementId: 'G-BBR1EMZR6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACtHysCjyrRfsf6QyUb9nwP9ysZuwKNtk',
    appId: '1:360971013353:android:3c5ef17d54d111be9e3478',
    messagingSenderId: '360971013353',
    projectId: 'newsbaseapp',
    storageBucket: 'newsbaseapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqp5YytpBi9y3ipwguv4FDtwckF4cvsP4',
    appId: '1:360971013353:ios:cf961e49fdcad7b79e3478',
    messagingSenderId: '360971013353',
    projectId: 'newsbaseapp',
    storageBucket: 'newsbaseapp.appspot.com',
    iosBundleId: 'com.example.newsappLatest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBml3Z176WWdq-ZJ1Gb7v7pLQUhzKQFktY',
    appId: '1:1051700358679:ios:b3550aa7cad377b8547652',
    messagingSenderId: '1051700358679',
    projectId: 'newsappfinal-c9395',
    storageBucket: 'newsappfinal-c9395.appspot.com',
    iosBundleId: 'com.example.newsappLatest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlFz72kEDIT5ERv-R1xLv7EiUKrel55JI',
    appId: '1:360971013353:web:614d7289f386b9f29e3478',
    messagingSenderId: '360971013353',
    projectId: 'newsbaseapp',
    authDomain: 'newsbaseapp.firebaseapp.com',
    storageBucket: 'newsbaseapp.appspot.com',
    measurementId: 'G-9KE54Z834X',
  );

}